### PR TITLE
Adding ordering and other help to the english readme.

### PR DESCRIPTION
**Pull request by christrotter**
Added a few items that I found helpful to know when ordering...

- A note about mini LED naming differences
- A new section outlining ordering with both Elecrow and JLCPCB

### CODE REVIEW

**Comment by swanmatch** [comment]
Thanks @christrotter

**Comment by swanmatch** [comment]
@christrotter 
I merged them for now, but some of the tables in Ordering PCBs seem to be broken.
Please fix it if you can.
https://swanmatch.github.io/MxLEDBitPCB/readme_en.html

**Comment by christrotter** [comment]
@swanmatch The tables work in straight github.  I'll take a look at why github.io is not formatting properly...

**Comment by christrotter** [comment]
I think this... https://github.com/pages-themes/cayman/issues/82 (edit: did not actually end up using this)
Sending another PR.

**Comment by christrotter** [comment]
https://github.com/swanmatch/MxLEDBitPCB/pull/19

**Pull request merged**
